apiVersion: v1
kind: Service
metadata:
  name: {{ template "prosody.fullname" . }}
  labels:
    app: {{ template "prosody.name" . }}
    chart: {{ template "prosody.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.xmpp.c2s.port }}
      targetPort: xmpp-c2s
      protocol: TCP
      name: xmpp-c2s
    - port: {{ .Values.service.xmpp.s2s.port }}
      targetPort: xmpp-s2s
      protocol: TCP
      name: xmpp-s2s
    - port: {{ .Values.service.xmpp.component.port }}
      targetPort: xmpp-component
      protocol: TCP
      name: xmpp-component
    - port: {{ .Values.service.bosh.insecure.port }}
      targetPort: bosh-insecure
      protocol: TCP
      name: bosh-insecure
    - port: {{ .Values.service.bosh.secure.port }}
      targetPort: bosh-secure
      protocol: TCP
      name: bosh-secure
  selector:
    app: {{ template "prosody.name" . }}
    release: {{ .Release.Name }}
